In [38]:
# Read the CSV file.
# Display the first 5 records.
# Display the last 5 records.
# Display dataset shape.
# Display all column names.
# Display data types.
# Use info().
# Use describe().
# Find average Python marks.
# Find average SQL marks.
# Find average Pandas marks.
# Find maximum marks.
# Find minimum marks.
# Sort students by Python marks.
# Sort students by attendance.
# Filter students having Python marks greater than 80.
# Filter students having attendance greater than 75.
# Select only name, python_marks, and pandas_marks.
# Add a new column called total_marks.
# Add another column called average_marks.
#output/student_results.csv

In [39]:
data = {"name": ["Alice", "Bob", "Carol"], "age": [25, 30, 35]}

In [40]:
import pandas as pd

In [41]:
df= pd.DataFrame(data)

In [42]:
df #dataframe

    name  age
0  Alice   25
1    Bob   30
2  Carol   35

In [43]:
df= pd.read_csv("students.csv")

In [44]:
df

,student_id,name,age,city,python_marks,sql_marks,pandas_marks,attendance
0,S1000,Divya,19,Mumbai,64,80,78,81
1,S1001,Myra,21,Bangalore,99,67,66,87
2,S1002,Pooja,21,Kolkata,99,46,48,61
3,S1003,Navya,24,Ahmedabad,99,48,54,65
4,S1004,Krishna,23,Delhi,84,47,54,87
5,S1005,Ishaan,23,Pune,80,51,65,87
6,S1006,Manish,24,Bangalore,68,73,81,79
7,S1007,Amit,23,Mumbai,54,72,99,89
8,S1008,Saanvi,20,Ahmedabad,84,87,52,70
9,S1009,Aarav,21,Bangalore,40,94,90,87
10,S1010,Arjun,24,Mumbai,64,62,71,84
11,S1011,Anika,21,Chennai,46,63,78,98
12,S1012,Sai,18,Chennai,48,76,88,92
13,S1013,Aadhya,20,Nagpur,63,74,91,60
14,S1014,Diya,22,Bangalore,40,83,71,86
15,S1015,Neha,20,Chennai,83,79,43,72
16,S1016,Vivaan,24,Mumbai,47,61,69,62
17,S1017,Aditya,22,Nagpur,63,66,76,98
18,S1018,Sneha,18,Mumbai,50,74,62,65
19,S1019,Vihaan,24,Nagpur,90,40,78,67
20,S1020,Karan,19,Bangalore,56,74,84,86
21,S1021,Rahul,21,Ahmedabad,47,76,54,68
22,S1022,Riya,18,Kolkata,74,86,82,96
23,S1023,Kavya,21,Jaipur,74,53,68,92
24,S1024,Rohan,23,Ahmedabad,72,42,75,83
25,S1025,Ayaan,19,Hyderabad,98,40,52,74
26,S1026,Ananya,19,Mumbai,44,44,71,91
27,S1027,Kiara,18,Hyderabad,81,65,46,91
28,S1028,Priya,19,Ahmedabad,78,94,98,83
29,S1029,Reyansh,22,Nagpur,97,53,90,71

In [45]:
#Display the first 5 records.
df.head()

,student_id,name,age,city,python_marks,sql_marks,pandas_marks,attendance
0,S1000,Divya,19,Mumbai,64,80,78,81
1,S1001,Myra,21,Bangalore,99,67,66,87
2,S1002,Pooja,21,Kolkata,99,46,48,61
3,S1003,Navya,24,Ahmedabad,99,48,54,65
4,S1004,Krishna,23,Delhi,84,47,54,87

In [46]:
# Display the last 5 records.
df.tail()

,student_id,name,age,city,python_marks,sql_marks,pandas_marks,attendance
25,S1025,Ayaan,19,Hyderabad,98,40,52,74
26,S1026,Ananya,19,Mumbai,44,44,71,91
27,S1027,Kiara,18,Hyderabad,81,65,46,91
28,S1028,Priya,19,Ahmedabad,78,94,98,83
29,S1029,Reyansh,22,Nagpur,97,53,90,71

In [47]:
# Display dataset shape.
df.shape

(30, 8)

In [48]:
# Display all column names.
df.columns

Index(['student_id', 'name', 'age', 'city', 'python_marks', 'sql_marks',
       'pandas_marks', 'attendance'],
      dtype='str')

In [49]:
# Display data types.
# Use info().
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   student_id    30 non-null     str
 1   name          30 non-null     str
 2   age           30 non-null     int64
 3   city          30 non-null     str
 4   python_marks  30 non-null     int64
 5   sql_marks     30 non-null     int64
 6   pandas_marks  30 non-null     int64
 7   attendance    30 non-null     int64
dtypes: int64(5), str(3)
memory usage: 2.0 KB

In [50]:
#Use describe() _ columns which have numerical datatype 
df.describe()

             age  python_marks  sql_marks  pandas_marks  attendance
count  30.000000     30.000000  30.000000     30.000000   30.000000
mean   21.033333     69.533333  65.666667     71.133333   80.400000
std     2.059182     19.415126  16.240293     15.738670   11.660721
min    18.000000     40.000000  40.000000     43.000000   60.000000
25%    19.000000     51.000000  51.500000     56.000000   70.250000
50%    21.000000     70.000000  66.500000     71.000000   83.500000
75%    23.000000     83.750000  76.000000     81.750000   88.500000
max    24.000000     99.000000  94.000000     99.000000   98.000000

In [51]:
# Find average Python marks.

df.head()

,student_id,name,age,city,python_marks,sql_marks,pandas_marks,attendance
0,S1000,Divya,19,Mumbai,64,80,78,81
1,S1001,Myra,21,Bangalore,99,67,66,87
2,S1002,Pooja,21,Kolkata,99,46,48,61
3,S1003,Navya,24,Ahmedabad,99,48,54,65
4,S1004,Krishna,23,Delhi,84,47,54,87

In [52]:
df["python_marks"].mean()

np.float64(69.53333333333333)

In [53]:
# Find average SQL marks.
# Find average Pandas marks.
# Find maximum marks.
# Find minimum marks.

print(f"Avg of sql: {df["sql_marks"].mean()}")
print(f"avg of pandas: {df["pandas_marks"].mean()}")
print(f"max of padas: {df["pandas_marks"].max()}")

Avg of sql: 65.66666666666667
avg of pandas: 71.13333333333334
max of padas: 99

In [54]:
#  Sort students by Python marks.
# # Sort students by attendance

df.sort_values(by="python_marks",ascending=False)
df.sort_values(by="attendance")

,student_id,name,age,city,python_marks,sql_marks,pandas_marks,attendance
13,S1013,Aadhya,20,Nagpur,63,74,91,60
2,S1002,Pooja,21,Kolkata,99,46,48,61
16,S1016,Vivaan,24,Mumbai,47,61,69,62
3,S1003,Navya,24,Ahmedabad,99,48,54,65
18,S1018,Sneha,18,Mumbai,50,74,62,65
19,S1019,Vihaan,24,Nagpur,90,40,78,67
21,S1021,Rahul,21,Ahmedabad,47,76,54,68
8,S1008,Saanvi,20,Ahmedabad,84,87,52,70
29,S1029,Reyansh,22,Nagpur,97,53,90,71
15,S1015,Neha,20,Chennai,83,79,43,72
25,S1025,Ayaan,19,Hyderabad,98,40,52,74
6,S1006,Manish,24,Bangalore,68,73,81,79
0,S1000,Divya,19,Mumbai,64,80,78,81
24,S1024,Rohan,23,Ahmedabad,72,42,75,83
28,S1028,Priya,19,Ahmedabad,78,94,98,83
10,S1010,Arjun,24,Mumbai,64,62,71,84
20,S1020,Karan,19,Bangalore,56,74,84,86
14,S1014,Diya,22,Bangalore,40,83,71,86
5,S1005,Ishaan,23,Pune,80,51,65,87
4,S1004,Krishna,23,Delhi,84,47,54,87
1,S1001,Myra,21,Bangalore,99,67,66,87
9,S1009,Aarav,21,Bangalore,40,94,90,87
7,S1007,Amit,23,Mumbai,54,72,99,89
27,S1027,Kiara,18,Hyderabad,81,65,46,91
26,S1026,Ananya,19,Mumbai,44,44,71,91
12,S1012,Sai,18,Chennai,48,76,88,92
23,S1023,Kavya,21,Jaipur,74,53,68,92
22,S1022,Riya,18,Kolkata,74,86,82,96
11,S1011,Anika,21,Chennai,46,63,78,98
17,S1017,Aditya,22,Nagpur,63,66,76,98

In [55]:
# Filter students having Python marks greater than 80.
# # Filter students having attendance greater than 75.

df[df["python_marks"]>80].sort_values(by="attendance" )

,student_id,name,age,city,python_marks,sql_marks,pandas_marks,attendance
2,S1002,Pooja,21,Kolkata,99,46,48,61
3,S1003,Navya,24,Ahmedabad,99,48,54,65
19,S1019,Vihaan,24,Nagpur,90,40,78,67
8,S1008,Saanvi,20,Ahmedabad,84,87,52,70
29,S1029,Reyansh,22,Nagpur,97,53,90,71
15,S1015,Neha,20,Chennai,83,79,43,72
25,S1025,Ayaan,19,Hyderabad,98,40,52,74
4,S1004,Krishna,23,Delhi,84,47,54,87
1,S1001,Myra,21,Bangalore,99,67,66,87
27,S1027,Kiara,18,Hyderabad,81,65,46,91

In [56]:
df[df["attendance"]>75]

,student_id,name,age,city,python_marks,sql_marks,pandas_marks,attendance
0,S1000,Divya,19,Mumbai,64,80,78,81
1,S1001,Myra,21,Bangalore,99,67,66,87
4,S1004,Krishna,23,Delhi,84,47,54,87
5,S1005,Ishaan,23,Pune,80,51,65,87
6,S1006,Manish,24,Bangalore,68,73,81,79
7,S1007,Amit,23,Mumbai,54,72,99,89
9,S1009,Aarav,21,Bangalore,40,94,90,87
10,S1010,Arjun,24,Mumbai,64,62,71,84
11,S1011,Anika,21,Chennai,46,63,78,98
12,S1012,Sai,18,Chennai,48,76,88,92
14,S1014,Diya,22,Bangalore,40,83,71,86
17,S1017,Aditya,22,Nagpur,63,66,76,98
20,S1020,Karan,19,Bangalore,56,74,84,86
22,S1022,Riya,18,Kolkata,74,86,82,96
23,S1023,Kavya,21,Jaipur,74,53,68,92
24,S1024,Rohan,23,Ahmedabad,72,42,75,83
26,S1026,Ananya,19,Mumbai,44,44,71,91
27,S1027,Kiara,18,Hyderabad,81,65,46,91
28,S1028,Priya,19,Ahmedabad,78,94,98,83

In [57]:
# Select only name, python_marks, and pandas_marks.
# # Add a new column called total_marks.
# # Add another column called average_marks.

type(df["name"])

pandas.Series

In [58]:
df[["name","python_marks", "pandas_marks"]]

       name  python_marks  pandas_marks
0     Divya            64            78
1      Myra            99            66
2     Pooja            99            48
3     Navya            99            54
4   Krishna            84            54
5    Ishaan            80            65
6    Manish            68            81
7      Amit            54            99
8    Saanvi            84            52
9     Aarav            40            90
10    Arjun            64            71
11    Anika            46            78
12      Sai            48            88
13   Aadhya            63            91
14     Diya            40            71
15     Neha            83            43
16   Vivaan            47            69
17   Aditya            63            76
18    Sneha            50            62
19   Vihaan            90            78
20    Karan            56            84
21    Rahul            47            54
22     Riya            74            82
23    Kavya            74            68
24    Rohan            72            75
25    Ayaan            98            52
26   Ananya            44            71
27    Kiara            81            46
28    Priya            78            98
29  Reyansh            97            90

In [59]:
type(df[["name","python_marks", "pandas_marks"]])

pandas.DataFrame

In [60]:
#Add a new column called total_marks.
df.head()

,student_id,name,age,city,python_marks,sql_marks,pandas_marks,attendance
0,S1000,Divya,19,Mumbai,64,80,78,81
1,S1001,Myra,21,Bangalore,99,67,66,87
2,S1002,Pooja,21,Kolkata,99,46,48,61
3,S1003,Navya,24,Ahmedabad,99,48,54,65
4,S1004,Krishna,23,Delhi,84,47,54,87

In [61]:
df["total_marks"]= df["python_marks"]+df["sql_marks"]+df["pandas_marks"]

In [62]:
df.head()

,student_id,name,age,city,python_marks,sql_marks,pandas_marks,attendance,total_marks
0,S1000,Divya,19,Mumbai,64,80,78,81,222
1,S1001,Myra,21,Bangalore,99,67,66,87,232
2,S1002,Pooja,21,Kolkata,99,46,48,61,193
3,S1003,Navya,24,Ahmedabad,99,48,54,65,201
4,S1004,Krishna,23,Delhi,84,47,54,87,185

In [63]:
# Add another column called average_marks.
df["average_marks"]= df["total_marks"]/3

In [64]:
df

,student_id,name,age,city,python_marks,sql_marks,pandas_marks,attendance,total_marks,average_marks
0,S1000,Divya,19,Mumbai,64,80,78,81,222,74.000000
1,S1001,Myra,21,Bangalore,99,67,66,87,232,77.333333
2,S1002,Pooja,21,Kolkata,99,46,48,61,193,64.333333
3,S1003,Navya,24,Ahmedabad,99,48,54,65,201,67.000000
4,S1004,Krishna,23,Delhi,84,47,54,87,185,61.666667
5,S1005,Ishaan,23,Pune,80,51,65,87,196,65.333333
6,S1006,Manish,24,Bangalore,68,73,81,79,222,74.000000
7,S1007,Amit,23,Mumbai,54,72,99,89,225,75.000000
8,S1008,Saanvi,20,Ahmedabad,84,87,52,70,223,74.333333
9,S1009,Aarav,21,Bangalore,40,94,90,87,224,74.666667
10,S1010,Arjun,24,Mumbai,64,62,71,84,197,65.666667
11,S1011,Anika,21,Chennai,46,63,78,98,187,62.333333
12,S1012,Sai,18,Chennai,48,76,88,92,212,70.666667
13,S1013,Aadhya,20,Nagpur,63,74,91,60,228,76.000000
14,S1014,Diya,22,Bangalore,40,83,71,86,194,64.666667
15,S1015,Neha,20,Chennai,83,79,43,72,205,68.333333
16,S1016,Vivaan,24,Mumbai,47,61,69,62,177,59.000000
17,S1017,Aditya,22,Nagpur,63,66,76,98,205,68.333333
18,S1018,Sneha,18,Mumbai,50,74,62,65,186,62.000000
19,S1019,Vihaan,24,Nagpur,90,40,78,67,208,69.333333
20,S1020,Karan,19,Bangalore,56,74,84,86,214,71.333333
21,S1021,Rahul,21,Ahmedabad,47,76,54,68,177,59.000000
22,S1022,Riya,18,Kolkata,74,86,82,96,242,80.666667
23,S1023,Kavya,21,Jaipur,74,53,68,92,195,65.000000
24,S1024,Rohan,23,Ahmedabad,72,42,75,83,189,63.000000
25,S1025,Ayaan,19,Hyderabad,98,40,52,74,190,63.333333
26,S1026,Ananya,19,Mumbai,44,44,71,91,159,53.000000
27,S1027,Kiara,18,Hyderabad,81,65,46,91,192,64.000000
28,S1028,Priya,19,Ahmedabad,78,94,98,83,270,90.000000
29,S1029,Reyansh,22,Nagpur,97,53,90,71,240,80.000000

In [65]:
df.to_csv("updted_student_data.csv")