In [1]:
# Read CSV.

# Inspect dataset.

# Find total products.

# Find unique categories.

# Find unique brands.

# Count products category-wise.

# Find average price.

# Find highest-priced product.

# Find lowest-priced product.

# Find products priced above ₹50,000.

# Find products with rating greater than 4.

# Sort products by price.

# Sort products by rating.

# Find products with stock below 10.

# Create discount_amount.

# Create final_price.

# Find average price by category.

# Find average rating by brand.

# Find maximum product price category-wise.

In [2]:
import pandas as pd

In [9]:
df= pd.read_csv("product_dataset.csv")

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    56 non-null     str
 1   product_name  56 non-null     str
 2   category      56 non-null     str
 3   brand         56 non-null     str
 4   price         56 non-null     float64
 5   rating        56 non-null     float64
 6   stock         56 non-null     int64
 7   discount      56 non-null     int64
dtypes: float64(2), int64(2), str(4)
memory usage: 3.6 KB

In [12]:
# Find total products.
print(df['product_id'].count())

56

In [13]:
# Find unique categories.
df['category'].value_counts()

category
Laptop         8
Keyboard       8
Mobile         8
Tablet         8
Monitor        8
Headphones     8
Accessories    8
Name: count, dtype: int64

In [14]:
# Find unique brands.
df['brand'].unique()

<StringArray>
[         'Dell',          'Acer',        'Realme',        'Amazon',
      'Logitech',          'Boat',          'Asus',          'Bose',
         'Apple',       'Samsung', 'Amazon Basics',         'Razer',
          'Sony',          'BenQ',          'ASUS',        'Belkin',
       'Corsair',            'LG',        'Huawei',           'MSI',
         'Anker',        'Ugreen',            'HP',    'Skullcandy',
          'Vivo']
Length: 25, dtype: str

In [15]:
df['brand'].value_counts()

brand
Acer             6
Realme           5
Samsung          5
Asus             4
Bose             4
Dell             3
Amazon Basics    3
Belkin           3
Amazon           2
Logitech         2
Boat             2
Apple            2
Razer            2
HP               2
Sony             1
BenQ             1
ASUS             1
Corsair          1
LG               1
Huawei           1
MSI              1
Anker            1
Ugreen           1
Skullcandy       1
Vivo             1
Name: count, dtype: int64

In [16]:
# Count products category-wise.
df["category"].value_counts()

category
Laptop         8
Keyboard       8
Mobile         8
Tablet         8
Monitor        8
Headphones     8
Accessories    8
Name: count, dtype: int64

In [18]:
# Find average price.
print(df['price'].mean())

34427.98553571429

In [21]:
# Find highest-priced product.
print(df['price'].max())
df[df['price']==df["price"].max()]

134055.15

,product_id,product_name,category,brand,price,rating,stock,discount
43,P0044,Asus Inspiron,Laptop,Asus,134055.15,3.9,25,0

In [22]:
# Find lowest-priced product.
df[df['price']==df["price"].min()]

,product_id,product_name,category,brand,price,rating,stock,discount
50,P0051,Amazon Basics Wireless Mouse,Accessories,Amazon Basics,333.8,4.3,30,10

In [23]:
# Find products priced above ₹50,000.
df[df['price']>= 50000]

,product_id,product_name,category,brand,price,rating,stock,discount
2,P0003,Acer Gaming Edge,Laptop,Acer,131927.97,4.4,117,0
13,P0014,Samsung MatePad,Tablet,Samsung,55275.67,3.8,398,0
15,P0016,Realme Nord Lite,Mobile,Realme,99762.56,4.9,272,5
21,P0022,Realme Galaxy Series,Mobile,Realme,84436.94,4.7,44,25
27,P0028,Asus UltraLight,Laptop,Asus,103527.17,3.7,128,0
35,P0036,Samsung V Series,Mobile,Samsung,103356.53,2.9,248,30
37,P0038,MSI Pro Book,Laptop,MSI,118919.16,3.8,498,25
42,P0043,Dell Pro Book,Laptop,Dell,133858.07,2.7,121,15
43,P0044,Asus Inspiron,Laptop,Asus,134055.15,3.9,25,0
51,P0052,HP Pro Book,Laptop,HP,62700.23,3.9,40,0
55,P0056,Vivo Note X,Mobile,Vivo,54128.13,2.7,467,20

In [24]:
# Find products with rating greater than 4.
df[df['rating']>4]

,product_id,product_name,category,brand,price,rating,stock,discount
1,P0002,Dell Wireless Slim,Keyboard,Dell,8734.23,4.3,214,10
2,P0003,Acer Gaming Edge,Laptop,Acer,131927.97,4.4,117,0
11,P0012,Asus IPS Panel,Monitor,Asus,17571.25,4.7,388,5
15,P0016,Realme Nord Lite,Mobile,Realme,99762.56,4.9,272,5
19,P0020,Razer Compact 60%,Keyboard,Razer,9185.55,4.2,365,15
21,P0022,Realme Galaxy Series,Mobile,Realme,84436.94,4.7,44,25
25,P0026,Samsung Air Tab,Tablet,Samsung,26395.89,4.9,296,0
26,P0027,Belkin SD Card 128GB,Accessories,Belkin,1051.92,4.2,305,0
30,P0031,Realme Redmi Pro,Mobile,Realme,22600.69,4.7,384,15
31,P0032,Belkin Cable Organizer,Accessories,Belkin,2083.44,5.0,327,10
33,P0034,Razer RGB Gaming,Keyboard,Razer,2105.75,4.4,275,15
38,P0039,Bose StudioMax,Headphones,Bose,12881.40,4.7,329,30
39,P0040,Samsung iPhone Series,Mobile,Samsung,42249.61,4.1,453,20
48,P0049,Samsung Surface Go,Tablet,Samsung,38597.98,4.4,440,0
49,P0050,HP RGB Gaming,Keyboard,HP,11154.96,4.5,146,25
50,P0051,Amazon Basics Wireless Mouse,Accessories,Amazon Basics,333.80,4.3,30,10

In [ ]:
# Sort products by price.
df.sort_values(by="price", ascending=False)

,product_id,product_name,category,brand,price,rating,stock,discount
43,P0044,Asus Inspiron,Laptop,Asus,134055.15,3.9,25,0
42,P0043,Dell Pro Book,Laptop,Dell,133858.07,2.7,121,15
2,P0003,Acer Gaming Edge,Laptop,Acer,131927.97,4.4,117,0
37,P0038,MSI Pro Book,Laptop,MSI,118919.16,3.8,498,25
27,P0028,Asus UltraLight,Laptop,Asus,103527.17,3.7,128,0
35,P0036,Samsung V Series,Mobile,Samsung,103356.53,2.9,248,30
15,P0016,Realme Nord Lite,Mobile,Realme,99762.56,4.9,272,5
21,P0022,Realme Galaxy Series,Mobile,Realme,84436.94,4.7,44,25
51,P0052,HP Pro Book,Laptop,HP,62700.23,3.9,40,0
13,P0014,Samsung MatePad,Tablet,Samsung,55275.67,3.8,398,0
55,P0056,Vivo Note X,Mobile,Vivo,54128.13,2.7,467,20
14,P0015,Amazon Tab S Series,Tablet,Amazon,48178.19,4.0,87,10
12,P0013,Apple Fire Tablet,Tablet,Apple,46511.87,3.9,51,0
10,P0011,Acer OLED Vision,Monitor,Acer,44826.06,3.9,367,30
47,P0048,Acer OLED Vision,Monitor,Acer,44398.28,2.7,206,20
0,P0001,Dell ZenBook,Laptop,Dell,44212.82,3.0,304,0
39,P0040,Samsung iPhone Series,Mobile,Samsung,42249.61,4.1,453,20
22,P0023,BenQ UltraWide 34,Monitor,BenQ,40079.71,3.2,327,10
48,P0049,Samsung Surface Go,Tablet,Samsung,38597.98,4.4,440,0
44,P0045,Acer Pro Book,Laptop,Acer,37876.24,3.2,114,5
3,P0004,Realme V Series,Mobile,Realme,35872.43,2.8,455,10
28,P0029,Realme Nord Lite,Mobile,Realme,33566.05,2.8,478,30
8,P0009,Asus OLED Vision,Monitor,Asus,31695.37,3.6,264,30
32,P0033,LG OLED Vision,Monitor,LG,31529.03,3.6,475,0
4,P0005,Amazon Fire Tablet,Tablet,Amazon,29095.53,2.9,490,20
25,P0026,Samsung Air Tab,Tablet,Samsung,26395.89,4.9,296,0
53,P0054,Acer IPS Panel,Monitor,Acer,23280.49,4.0,185,10
30,P0031,Realme Redmi Pro,Mobile,Realme,22600.69,4.7,384,15
45,P0046,Apple Air Tab,Tablet,Apple,21931.23,3.3,301,10
6,P0007,Acer Business View,Monitor,Acer,20863.62,3.4,107,15
34,P0035,Boat SoundWave,Headphones,Boat,17850.64,2.6,116,15
11,P0012,Asus IPS Panel,Monitor,Asus,17571.25,4.7,388,5
36,P0037,Huawei Pad Lite,Tablet,Huawei,14774.68,3.0,274,30
38,P0039,Bose StudioMax,Headphones,Bose,12881.40,4.7,329,30
18,P0019,Bose StudioMax,Headphones,Bose,12301.83,3.9,135,25
9,P0010,Bose SportFit,Headphones,Bose,12245.95,3.5,48,0
49,P0050,HP RGB Gaming,Keyboard,HP,11154.96,4.5,146,25
5,P0006,Logitech TypeMaster,Keyboard,Logitech,10572.31,3.2,256,5
16,P0017,Bose SportFit,Headphones,Bose,10505.18,2.6,194,0
19,P0020,Razer Compact 60%,Keyboard,Razer,9185.55,4.2,365,15
54,P0055,Skullcandy StudioMax,Headphones,Skullcandy,9032.25,3.2,80,30
1,P0002,Dell Wireless Slim,Keyboard,Dell,8734.23,4.3,214,10
29,P0030,Corsair Wireless Slim,Keyboard,Corsair,8201.85,3.3,135,25
24,P0025,ASUS Ergo Comfort,Keyboard,ASUS,4574.42,3.5,442,0
52,P0053,Logitech SilentTouch,Keyboard,Logitech,3177.10,2.8,142,30
20,P0021,Sony NoiseCancel Pro,Headphones,Sony,3067.42,3.1,308,0
23,P0024,Amazon Basics Wireless Mouse,Accessories,Amazon Basics,2677.66,2.8,178,0
17,P0018,Amazon Basics Power Bank,Accessories,Amazon Basics,2596.45,2.8,185,15
33,P0034,Razer RGB Gaming,Keyboard,Razer,2105.75,4.4,275,15
40,P0041,Anker USB-C Hub,Accessories,Anker,2085.66,3.4,176,15
31,P0032,Belkin Cable Organizer,Accessories,Belkin,2083.44,5.0,327,10
7,P0008,Boat ClearTone,Headphones,Boat,1761.75,2.7,336,20
46,P0047,Belkin Cable Organizer,Accessories,Belkin,1162.39,3.7,447,0
26,P0027,Belkin SD Card 128GB,Accessories,Belkin,1051.92,4.2,305,0
41,P0042,Ugreen Power Bank,Accessories,Ugreen,568.68,4.0,257,5
50,P0051,Amazon Basics Wireless Mouse,Accessories,Amazon Basics,333.80,4.3,30,10

In [27]:
# Sort products by rating.
df.sort_values(by="rating")

,product_id,product_name,category,brand,price,rating,stock,discount
16,P0017,Bose SportFit,Headphones,Bose,10505.18,2.6,194,0
34,P0035,Boat SoundWave,Headphones,Boat,17850.64,2.6,116,15
42,P0043,Dell Pro Book,Laptop,Dell,133858.07,2.7,121,15
7,P0008,Boat ClearTone,Headphones,Boat,1761.75,2.7,336,20
55,P0056,Vivo Note X,Mobile,Vivo,54128.13,2.7,467,20
47,P0048,Acer OLED Vision,Monitor,Acer,44398.28,2.7,206,20
17,P0018,Amazon Basics Power Bank,Accessories,Amazon Basics,2596.45,2.8,185,15
3,P0004,Realme V Series,Mobile,Realme,35872.43,2.8,455,10
28,P0029,Realme Nord Lite,Mobile,Realme,33566.05,2.8,478,30
23,P0024,Amazon Basics Wireless Mouse,Accessories,Amazon Basics,2677.66,2.8,178,0
52,P0053,Logitech SilentTouch,Keyboard,Logitech,3177.10,2.8,142,30
35,P0036,Samsung V Series,Mobile,Samsung,103356.53,2.9,248,30
4,P0005,Amazon Fire Tablet,Tablet,Amazon,29095.53,2.9,490,20
36,P0037,Huawei Pad Lite,Tablet,Huawei,14774.68,3.0,274,30
0,P0001,Dell ZenBook,Laptop,Dell,44212.82,3.0,304,0
20,P0021,Sony NoiseCancel Pro,Headphones,Sony,3067.42,3.1,308,0
44,P0045,Acer Pro Book,Laptop,Acer,37876.24,3.2,114,5
5,P0006,Logitech TypeMaster,Keyboard,Logitech,10572.31,3.2,256,5
22,P0023,BenQ UltraWide 34,Monitor,BenQ,40079.71,3.2,327,10
54,P0055,Skullcandy StudioMax,Headphones,Skullcandy,9032.25,3.2,80,30
45,P0046,Apple Air Tab,Tablet,Apple,21931.23,3.3,301,10
29,P0030,Corsair Wireless Slim,Keyboard,Corsair,8201.85,3.3,135,25
6,P0007,Acer Business View,Monitor,Acer,20863.62,3.4,107,15
40,P0041,Anker USB-C Hub,Accessories,Anker,2085.66,3.4,176,15
9,P0010,Bose SportFit,Headphones,Bose,12245.95,3.5,48,0
24,P0025,ASUS Ergo Comfort,Keyboard,ASUS,4574.42,3.5,442,0
32,P0033,LG OLED Vision,Monitor,LG,31529.03,3.6,475,0
8,P0009,Asus OLED Vision,Monitor,Asus,31695.37,3.6,264,30
27,P0028,Asus UltraLight,Laptop,Asus,103527.17,3.7,128,0
46,P0047,Belkin Cable Organizer,Accessories,Belkin,1162.39,3.7,447,0
37,P0038,MSI Pro Book,Laptop,MSI,118919.16,3.8,498,25
13,P0014,Samsung MatePad,Tablet,Samsung,55275.67,3.8,398,0
18,P0019,Bose StudioMax,Headphones,Bose,12301.83,3.9,135,25
10,P0011,Acer OLED Vision,Monitor,Acer,44826.06,3.9,367,30
51,P0052,HP Pro Book,Laptop,HP,62700.23,3.9,40,0
12,P0013,Apple Fire Tablet,Tablet,Apple,46511.87,3.9,51,0
43,P0044,Asus Inspiron,Laptop,Asus,134055.15,3.9,25,0
53,P0054,Acer IPS Panel,Monitor,Acer,23280.49,4.0,185,10
14,P0015,Amazon Tab S Series,Tablet,Amazon,48178.19,4.0,87,10
41,P0042,Ugreen Power Bank,Accessories,Ugreen,568.68,4.0,257,5
39,P0040,Samsung iPhone Series,Mobile,Samsung,42249.61,4.1,453,20
26,P0027,Belkin SD Card 128GB,Accessories,Belkin,1051.92,4.2,305,0
19,P0020,Razer Compact 60%,Keyboard,Razer,9185.55,4.2,365,15
50,P0051,Amazon Basics Wireless Mouse,Accessories,Amazon Basics,333.80,4.3,30,10
1,P0002,Dell Wireless Slim,Keyboard,Dell,8734.23,4.3,214,10
48,P0049,Samsung Surface Go,Tablet,Samsung,38597.98,4.4,440,0
2,P0003,Acer Gaming Edge,Laptop,Acer,131927.97,4.4,117,0
33,P0034,Razer RGB Gaming,Keyboard,Razer,2105.75,4.4,275,15
49,P0050,HP RGB Gaming,Keyboard,HP,11154.96,4.5,146,25
21,P0022,Realme Galaxy Series,Mobile,Realme,84436.94,4.7,44,25
11,P0012,Asus IPS Panel,Monitor,Asus,17571.25,4.7,388,5
30,P0031,Realme Redmi Pro,Mobile,Realme,22600.69,4.7,384,15
38,P0039,Bose StudioMax,Headphones,Bose,12881.40,4.7,329,30
15,P0016,Realme Nord Lite,Mobile,Realme,99762.56,4.9,272,5
25,P0026,Samsung Air Tab,Tablet,Samsung,26395.89,4.9,296,0
31,P0032,Belkin Cable Organizer,Accessories,Belkin,2083.44,5.0,327,10

In [28]:
# Find products with stock below 10.
df[df['stock']<10]

Empty DataFrame
Columns: [product_id, product_name, category, brand, price, rating, stock, discount]
Index: []

In [30]:
# Create discount_amount.
df["discount_amount"]= df["discount"]*df["price"]*0.01
df.head()

,product_id,product_name,category,brand,price,rating,stock,discount,discount_amount
0,P0001,Dell ZenBook,Laptop,Dell,44212.82,3.0,304,0,0.000
1,P0002,Dell Wireless Slim,Keyboard,Dell,8734.23,4.3,214,10,873.423
2,P0003,Acer Gaming Edge,Laptop,Acer,131927.97,4.4,117,0,0.000
3,P0004,Realme V Series,Mobile,Realme,35872.43,2.8,455,10,3587.243
4,P0005,Amazon Fire Tablet,Tablet,Amazon,29095.53,2.9,490,20,5819.106

In [ ]:
# Create final_price for 1 item
df["final_price"]=df['price']-df['discount_amount']
df.head()

,product_id,product_name,category,brand,price,rating,stock,discount,discount_amount,final_price
0,P0001,Dell ZenBook,Laptop,Dell,44212.82,3.0,304,0,0.000,44212.820
1,P0002,Dell Wireless Slim,Keyboard,Dell,8734.23,4.3,214,10,873.423,7860.807
2,P0003,Acer Gaming Edge,Laptop,Acer,131927.97,4.4,117,0,0.000,131927.970
3,P0004,Realme V Series,Mobile,Realme,35872.43,2.8,455,10,3587.243,32285.187
4,P0005,Amazon Fire Tablet,Tablet,Amazon,29095.53,2.9,490,20,5819.106,23276.424

In [32]:
# Find average price by category.
df.groupby(by= "category")['price'].mean()

category
Accessories     1570.00000
Headphones      9955.80250
Keyboard        7213.27125
Laptop         95884.60125
Mobile         59496.61750
Monitor        31780.47625
Tablet         35095.13000
Name: price, dtype: float64

In [33]:
# Find average rating by brand.
df.groupby(by= "brand")['rating'].mean()

brand
ASUS             3.500000
Acer             3.600000
Amazon           3.450000
Amazon Basics    3.300000
Anker            3.400000
Apple            3.600000
Asus             3.975000
Belkin           4.300000
BenQ             3.200000
Boat             2.650000
Bose             3.675000
Corsair          3.300000
Dell             3.333333
HP               4.200000
Huawei           3.000000
LG               3.600000
Logitech         3.000000
MSI              3.800000
Razer            4.300000
Realme           3.980000
Samsung          4.020000
Skullcandy       3.200000
Sony             3.100000
Ugreen           4.000000
Vivo             2.700000
Name: rating, dtype: float64

In [34]:
# Find maximum product price category-wise.
df.groupby(by="category")['price'].max()

category
Accessories      2677.66
Headphones      17850.64
Keyboard        11154.96
Laptop         134055.15
Mobile         103356.53
Monitor         44826.06
Tablet          55275.67
Name: price, dtype: float64

In [35]:
df.head()

,product_id,product_name,category,brand,price,rating,stock,discount,discount_amount,final_price
0,P0001,Dell ZenBook,Laptop,Dell,44212.82,3.0,304,0,0.000,44212.820
1,P0002,Dell Wireless Slim,Keyboard,Dell,8734.23,4.3,214,10,873.423,7860.807
2,P0003,Acer Gaming Edge,Laptop,Acer,131927.97,4.4,117,0,0.000,131927.970
3,P0004,Realme V Series,Mobile,Realme,35872.43,2.8,455,10,3587.243,32285.187
4,P0005,Amazon Fire Tablet,Tablet,Amazon,29095.53,2.9,490,20,5819.106,23276.424

In [36]:
df.to_csv("updated_product_dataset.csv")